default: &default
  adapter: postgresql
  encoding: unicode

production:
  <<: *default
  database: microservice_sinatra_production
  host: <%= ENV['DATABASE_HOST'] %>

  database: <%= ENV["DATABASE_URL"] %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test: 
  <<: *default
  database: microservice_sinatra_test

#when deploying, remember this was important: `rake db:environment:set`
