default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: microservice_sinatra_development

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test: 
  <<: *default
  database: microservice_sinatra_test

#when deploying, remember this was important: `rake db:environment:set`