default: &default
  adapter: postgresql
  encoding: unicode

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development: 
  <<: *default
  database: microservice_sinatra_development

test: 
  <<: *default
  database: microservice_sinatra_test

#when deploying, remember this was important: `rake db:environment:set`
