default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: microservice_sinatra_development

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

test: 
  <<: *default
  database: microservice_sinatra_test

#when deploying, remember this was important: `rake db:environment:set`
