default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: microservice_sinatra_development

production:
  <<: *default

  database: <%= ENV["DATABASE_URL"] %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"]%>

test: 
  <<: *default
  database: microservice_sinatra_test

#when deploying, remember this was important: `rake db:environment:set`
